image: atlassian/default-image:4

clone:
  depth: full

pipelines:
  branches:
    add-more-led-on-silikka54:
      - step:
          name: Mirror Bitbucket to GitHub
          script:
            - export GITHUB_REMOTE="git@github.com:Lqhuy125/qmk_firmware.git"

            - git config user.name "Bitbucket Mirror Bot"
            - git config user.email "bitbucket-mirror-bot@users.noreply.github.com"

            - git remote add github "$GITHUB_REMOTE"

            # Prevent GitHub -> Bitbucket -> GitHub loop
            - |
              if git ls-remote "$GITHUB_REMOTE" "$BITBUCKET_COMMIT" | grep -q "$BITBUCKET_COMMIT"; then
                echo "Commit already exists on GitHub."
                echo "Skipping push - loop prevention."
                exit 0
              fi

            - echo "Commit does not exist on GitHub."
            - echo "Pushing Bitbucket -> GitHub..."

            - git push github HEAD:add-more-led-on-silikka54