name: Mirror to Bitbucket

on:
  push:
    branches:
      - add-more-led-on-silikka54

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Mirror Bot"
          git config user.email "github-mirror-bot@users.noreply.github.com"

      - name: Push to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
        run: |
          git remote add bitbucket \
            "https://x-token-auth:${BITBUCKET_TOKEN}@bitbucket.org/lqhuy125/qmk_firmware.git"

          git push bitbucket \
            HEAD:add-more-led-on-silikka54
